import { useEffect, useState } from 'react';import { makeLocalDeck, type LocalCard } from './engine/local';import type { MemoryPair } from './types';import { MemoryBoard } from './components/MemoryBoard';import { MemoryScoreboard } from './components/MemoryScoreboard';
export function LocalMemory({pairs,errors}:{pairs:MemoryPair[];errors:string[]}){const [names,setNames]=useState('Spieler 1, Spieler 2'),[deck,setDeck]=useState<LocalCard[]|null>(null),[scores,setScores]=useState<number[]>([]),[turn,setTurn]=useState(0),[picks,setPicks]=useState<number[]>([]),[locked,setLocked]=useState(false),[notice,setNotice]=useState<string|null>(null);const players=names.split(',').map(s=>s.trim()).filter(Boolean).slice(0,6);
function start(){setDeck(makeLocalDeck(pairs));setScores(players.map(()=>0));setTurn(0);setPicks([]);setLocked(false);setNotice(null)}
function flip(id:number){if(!deck||locked)return;const card=deck.find(c=>c.id===id);if(!card||card.visible||card.matched)return;setDeck(deck.map(c=>c.id===id?{...c,visible:true}:c));setPicks(p=>[...p,id])}
useEffect(()=>{if(!deck||picks.length!==2)return;const [a,b]=picks.map(id=>deck.find(c=>c.id===id)!);const match=a.pairId===b.pairId;setLocked(true);setNotice(match?'Richtig! Ein Paar gefunden!':'Das passt leider nicht!');if(match){setDeck(deck.map(c=>picks.includes(c.id)?{...c,matched:true}:c));setScores(s=>s.map((v,i)=>i===turn?v+1:v))}
const timer=window.setTimeout(()=>{if(!match){setDeck(d=>d?.map(c=>picks.includes(c.id)?{...c,visible:false}:c)||null);setTurn(t=>(t+1)%players.length)}setPicks([]);setLocked(false);setNotice(null)},1800);return()=>window.clearTimeout(timer)
// Intentionally resolve once per second pick, not per score update.
// eslint-disable-next-line react-hooks/exhaustive-deps
},[picks.length===2]);
const complete=!!deck&&deck.every(c=>c.matched);return !deck?<div className="form"><h2>Lokal spielen</h2><label>Spielernamen (durch Komma getrennt)<input className="field" value={names} onChange={e=>setNames(e.target.value)} /></label><button className="button primary" disabled={!!errors.length||pairs.length<1||players.length<1} onClick={start}>Spiel starten</button></div>:<div className="local-play"><div className="row"><h2>{complete?'Spiel beendet!':'Lokales Spiel'}</h2><button className="button secondary" onClick={()=>setDeck(null)}>Beenden</button></div><MemoryScoreboard players={players.map((name,i)=>({id:String(i),name,score:scores[i]}))} activeId={String(turn)}/><p>{deck.filter(c=>c.matched).length/2} / {pairs.length} Paare gefunden</p><MemoryBoard cards={deck} canFlip={!locked&&!complete} notice={notice} onFlip={flip}/></div>}
